/*
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ncloud.auth;

import com.ncloud.exception.SdkException;
import org.apache.hc.client5.http.async.methods.SimpleHttpRequest;

/**
 * The type Default credentials.
 */
public class DefaultCredentials implements Credentials {
	private String apiKey;

	/**
	 * Instantiates a new Default credentials.
	 *
	 * @param apiKey the api key
	 */
	protected DefaultCredentials(String apiKey) {
		if (apiKey == null) {
			throw new SdkException("Api Key cannot be null.");
		}
		this.apiKey = apiKey;
	}

	public void applyCredentials(SimpleHttpRequest request, boolean isRequiredApiKey) {
		if (isRequiredApiKey) {
			request.addHeader("x-ncp-apigw-api-key", apiKey);
		}
    }
}
